steps:
  - subject: pipeline.metrics
    pattern: publish
    direction: outgoing
    order: 1

  - subject: trace.header
    pattern: request
    direction: incoming
    order: 2

  - subject: pipeline.logging
    pattern: publish
    direction: outgoing
    order: 3

  - subject: authentication
    pattern: request
    direction: incoming
    order: 4

  - subject: '*'
    pattern: request
    direction: incoming
    order: 5